import type { NightRequestTemplate, ScriptNightTemplatePack } from './live-room';

const templatePacks: ScriptNightTemplatePack[] = [
  {
    scriptId: 'trouble_brewing',
    templates: [
      {
        templateId: 'tb-washerwoman',
        scriptId: 'trouble_brewing',
        roleId: 'washerwoman',
        label: '洗衣妇：查看两人中的一名镇民',
        actionType: 'select_two_players',
        prompt: '请选择两名玩家作为洗衣妇结果展示对象',
        description: '说书人随后向玩家展示这两人中有一人是指定镇民身份。',
        options: { minSelections: 2, maxSelections: 2 },
      },
      {
        templateId: 'tb-librarian',
        scriptId: 'trouble_brewing',
        roleId: 'librarian',
        label: '图书管理员：查看两人中的一名外来者',
        actionType: 'select_two_players',
        prompt: '请选择两名玩家作为图书管理员结果展示对象',
        description: '说书人随后向玩家展示这两人中有一人是指定外来者身份。',
        options: { minSelections: 2, maxSelections: 2 },
      },
      {
        templateId: 'tb-investigator',
        scriptId: 'trouble_brewing',
        roleId: 'investigator',
        label: '调查员：查看两人中的一名爪牙',
        actionType: 'select_two_players',
        prompt: '请选择两名玩家作为调查员结果展示对象',
        description: '说书人随后向玩家展示这两人中有一人是指定爪牙身份。',
        options: { minSelections: 2, maxSelections: 2 },
      },
      {
        templateId: 'tb-chef',
        scriptId: 'trouble_brewing',
        roleId: 'chef',
        label: '厨师：回传相邻邪恶对数',
        actionType: 'confirm_only',
        prompt: '请输入厨师今夜应得到的相邻邪恶对数',
        description: '创建后在裁定区直接回传数字结果即可。',
      },
      {
        templateId: 'tb-empath',
        scriptId: 'trouble_brewing',
        roleId: 'empath',
        label: '共情者：回传相邻邪恶人数',
        actionType: 'confirm_only',
        prompt: '请输入共情者今晚应得到的相邻邪恶人数',
        description: '常用于每夜重复回传信息。',
      },
      {
        templateId: 'tb-fortune-teller',
        scriptId: 'trouble_brewing',
        roleId: 'fortune_teller',
        label: '占卜师：选择两名玩家',
        actionType: 'select_two_players',
        prompt: '请选择占卜师今晚要占卜的两名玩家',
        description: '说书人随后裁定其中是否有恶魔或红鲱鱼。',
        options: { minSelections: 2, maxSelections: 2 },
      },
      {
        templateId: 'tb-monk',
        scriptId: 'trouble_brewing',
        roleId: 'monk',
        label: '僧侣：保护一名玩家',
        actionType: 'select_one_player',
        prompt: '请选择僧侣今晚保护的目标',
        description: '裁定时可附带 protected 状态标签。',
        options: { minSelections: 1, maxSelections: 1 },
      },
      {
        templateId: 'tb-ravenkeeper',
        scriptId: 'trouble_brewing',
        roleId: 'ravenkeeper',
        label: '渡鸦守护者：查看一名玩家身份',
        actionType: 'select_one_player',
        prompt: '请选择渡鸦守护者查看的目标',
        description: '适用于夜里死亡后临时创建的请求。',
        options: { minSelections: 1, maxSelections: 1 },
      },
      {
        templateId: 'tb-poisoner',
        scriptId: 'trouble_brewing',
        roleId: 'poisoner',
        label: '投毒者：选择一名中毒目标',
        actionType: 'select_one_player',
        prompt: '请选择投毒者今晚的目标',
        description: '裁定时可附带 poisoned 状态变更。',
        options: { minSelections: 1, maxSelections: 1 },
      },
      {
        templateId: 'tb-imp',
        scriptId: 'trouble_brewing',
        roleId: 'imp',
        label: '恶魔：选择击杀目标',
        actionType: 'select_one_player',
        prompt: '请选择恶魔今晚要击杀的目标',
        description: '裁定时可附带 alive=false 的状态变更。',
        options: { minSelections: 1, maxSelections: 1 },
      },
    ],
  },
  {
    scriptId: 'sects_and_violets',
    templates: [
      {
        templateId: 'sv-clockmaker',
        scriptId: 'sects_and_violets',
        roleId: 'clockmaker',
        label: '钟表匠：回传爪牙与恶魔间距',
        actionType: 'confirm_only',
        prompt: '请输入钟表匠应得到的间距数字',
        description: '用于首夜信息回传。',
      },
      {
        templateId: 'sv-dreamer',
        scriptId: 'sects_and_violets',
        roleId: 'dreamer',
        label: '梦语者：查看一名玩家的真假身份',
        actionType: 'select_one_player',
        prompt: '请选择梦语者今晚查看的目标',
        description: '裁定时向玩家回传一个真身份和一个假身份。',
        options: { minSelections: 1, maxSelections: 1 },
      },
      {
        templateId: 'sv-flowergirl',
        scriptId: 'sects_and_violets',
        roleId: 'flowergirl',
        label: '花女：回传恶魔是否投票',
        actionType: 'confirm_only',
        prompt: '请输入花女今晚的投票结果提示',
        description: '一般在白天投票后，于夜间回传 yes/no 信息。',
      },
      {
        templateId: 'sv-town-crier',
        scriptId: 'sects_and_violets',
        roleId: 'town_crier',
        label: '镇长侍从：回传爪牙是否提名',
        actionType: 'confirm_only',
        prompt: '请输入镇长侍从今晚的提名结果提示',
        description: '一般在白天提名后，于夜间回传 yes/no 信息。',
      },
      {
        templateId: 'sv-seamstress',
        scriptId: 'sects_and_violets',
        roleId: 'seamstress',
        label: '裁缝：选择两名玩家判断阵营',
        actionType: 'select_two_players',
        prompt: '请选择裁缝今晚要查看的两名玩家',
        description: '裁定时回传两人是否同阵营。',
        options: { minSelections: 2, maxSelections: 2 },
      },
      {
        templateId: 'sv-sage',
        scriptId: 'sects_and_violets',
        roleId: 'sage',
        label: '贤者：死亡后查看两名恶魔候选',
        actionType: 'select_two_players',
        prompt: '请选择贤者要看到的两名候选玩家',
        description: '适用于贤者触发后的补发请求。',
        options: { minSelections: 2, maxSelections: 2 },
      },
      {
        templateId: 'sv-snake-charmer',
        scriptId: 'sects_and_violets',
        roleId: 'snake_charmer',
        label: '驭蛇人：选择一名玩家',
        actionType: 'select_one_player',
        prompt: '请选择驭蛇人今晚尝试交换的目标',
        description: '如发生角色变化，可在裁定时附带 status_tag 或 disabled 备注。',
        options: { minSelections: 1, maxSelections: 1 },
      },
      {
        templateId: 'sv-cerenovus',
        scriptId: 'sects_and_violets',
        roleId: 'cerenovus',
        label: '塞瑞诺沃斯：指定疯狂角色',
        actionType: 'select_role',
        prompt: '请选择塞瑞诺沃斯今晚指定的角色',
        description: '裁定时可补充 mad/status_tag 状态说明。',
      },
      {
        templateId: 'sv-pit-hag',
        scriptId: 'sects_and_violets',
        roleId: 'pit_hag',
        label: '造角者：选择角色变化目标',
        actionType: 'select_role',
        prompt: '请选择造角者今晚要制造的新角色',
        description: '建议配合备注写清变更对象，并在裁定时附带 status_tag。',
      },
      {
        templateId: 'sv-fang-gu',
        scriptId: 'sects_and_violets',
        roleId: 'fang_gu',
        label: '方古：选择攻击目标',
        actionType: 'select_one_player',
        prompt: '请选择方古今晚的攻击目标',
        description: '如发生跳恶魔或死亡，可在裁定时附带 alive/status_tag 变更。',
        options: { minSelections: 1, maxSelections: 1 },
      },
    ],
  },
];

export function getNightRequestTemplates(scriptId: string): NightRequestTemplate[] {
  return templatePacks.find((pack) => pack.scriptId === scriptId)?.templates ?? [];
}

export function getNightRequestTemplate(scriptId: string, templateId: string): NightRequestTemplate | undefined {
  return getNightRequestTemplates(scriptId).find((template) => template.templateId === templateId);
}
